services:
  mysql:
    image: mysql:8.0
    container_name: database-mysql
    restart: unless-stopped
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234                # contraseña del usuario adicional
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql            # carpeta local donde se guardan los datos
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

volumes:
  mysql_data:
